name: Varbase Security Base
description: A recipe to manage default security configurations including password policy, username enumeration prevention, security kit, CAPTCHA, honeypot, antibot, and flood control.
type: Varbase Security
install:
  - captcha
  - recaptcha
  - honeypot
  - antibot
  - password_policy
  - password_policy_character_types
  - password_policy_characters
  - password_policy_history
  - password_policy_length
  - password_policy_username
  - seckit
  - username_enumeration_prevention
  - flood_control
config:
  import:
    captcha: '*'
    recaptcha: '*'
    honeypot: '*'
    antibot: '*'
    password_policy: '*'
    seckit: '*'
    flood_control: '*'
  actions:
    user.flood:
      simpleConfigUpdate:
        uid_only: false
        ip_limit: 5
        ip_window: 1800
        user_limit: 4
        user_window: 1800
    user.role.anonymous:
      grantPermissions:
        - 'use klaro'
    user.role.authenticated:
      grantPermissions:
        - 'bypass honeypot protection'
        - 'skip CAPTCHA'
        - 'use klaro'
    user.role.content_editor:
      grantPermissions:
        - 'skip antibot'
    user.role.content_admin:
      grantPermissions:
        - 'skip antibot'
    user.role.seo_admin:
      grantPermissions:
        - 'skip antibot'
    user.role.site_admin:
      grantPermissions:
        - 'administer flood unblock'
        - 'flood unblock ips'
        - 'skip antibot'
