name: Varbase Security Base
description: A recipe to manage default security configurations including password policy, username enumeration prevention, security kit, CAPTCHA, honeypot, antibot, and flood control.
type: Varbase Security
install:
  - captcha
  - recaptcha
  - honeypot
  - antibot
  - password_policy
  - password_policy_character_types
  - password_policy_characters
  - password_policy_history
  - password_policy_length
  - password_policy_username
  - seckit
  - username_enumeration_prevention
  - flood_control
config:
  actions:
    user.flood:
      simpleConfigUpdate:
        uid_only: false
        ip_limit: 5
        ip_window: 1800
        user_limit: 4
        user_window: 1800
    user.settings:
      simpleConfigUpdate:
        anonymous: Anonymous
        verify_mail: true
        notify:
          cancel_confirm: true
          password_reset: true
          status_activated: true
          status_blocked: false
          status_canceled: false
          register_admin_created: true
          register_no_approval_required: true
          register_pending_approval: true
        register: admin_only
        cancel_method: user_cancel_block
        password_reset_timeout: 86400
        password_strength: true
        langcode: en
