name: Varbase Security Base
description: A recipe to manage default security configurations including password policy, username enumeration prevention, security kit, CAPTCHA, honeypot, antibot, and flood control.
type: Varbase Security
install:
  - captcha
  - recaptcha
  - honeypot
  - antibot
  - password_policy
  - password_policy_character_types
  - password_policy_characters
  - password_policy_history
  - password_policy_length
  - password_policy_username
  - seckit
  - username_enumeration_prevention
  - flood_control
